name: Deno CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Use deno v1.x on ${{ matrix.os }}
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - run: deno lint
    - run: deno run --allow-read mod.ts
